//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhGiaHangHoa
    {
        public System.Guid ID { get; set; }
        public System.Guid HangHoaID { get; set; }
        public System.Guid DonViID { get; set; }
        public Nullable<decimal> GiaDichVu { get; set; }
        public Nullable<decimal> GiaBaoHiem { get; set; }
        public string MaNguoiDinhGia { get; set; }
        public string TenNguoiDinhGia { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
        public string GhiChu { get; set; }
    }
}
