//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public System.Guid ID { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string TenKhac { get; set; }
        public string HoatChat { get; set; }
        public string DuongDung { get; set; }
        public string HamLuong { get; set; }
        public string DongGoi { get; set; }
        public Nullable<int> LoaiThuoc { get; set; }
        public string NguyCoThuoc { get; set; }
        public string HoTriLieu { get; set; }
        public Nullable<System.Guid> DonViID { get; set; }
        public Nullable<int> OldID { get; set; }
        public Nullable<int> MaBHThamChieu { get; set; }
        public string PhanLoaiDuocID { get; set; }
        public Nullable<int> MaNhomBaoHiem { get; set; }
        public Nullable<bool> ThanhToanBaoHiem { get; set; }
        public string TyLeThanhToanBaoHiem { get; set; }
    }
}
