//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_CaNhan
    {
        public System.Guid ID { get; set; }
        public string MA_HSBV { get; set; }
        public string HO_TEN { get; set; }
        public string TEN { get; set; }
        public Nullable<int> NGAY_SINH { get; set; }
        public Nullable<int> THANG_SINH { get; set; }
        public int NAM_SINH { get; set; }
        public Nullable<int> GIOI_TINH { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<int> MA_QGIA { get; set; }
        public string MA_TINH { get; set; }
        public string MA_HUYEN { get; set; }
        public string MA_XA { get; set; }
        public Nullable<int> DAN_TOC { get; set; }
        public Nullable<int> TON_GIAO { get; set; }
        public string CMND { get; set; }
        public string NGHE_NGHIEP { get; set; }
        public string NHOM_MAU { get; set; }
        public string DIEN_THOAI { get; set; }
        public string HO_TEN_NCSC { get; set; }
        public string MOI_QH_NCSC { get; set; }
        public string DIEN_THOAI_NCSC { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<bool> InActive { get; set; }
    }
}
