//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KhoChungEntities : DbContext
    {
        public KhoChungEntities()
            : base("name=KhoChungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenDoiDonViHangHoa> ChuyenDoiDonViHangHoa { get; set; }
        public virtual DbSet<DonViHangHoa> DonViHangHoa { get; set; }
        public virtual DbSet<HangHoa> HangHoa { get; set; }
        public virtual DbSet<LoaiGiaHangHoa> LoaiGiaHangHoa { get; set; }
        public virtual DbSet<LoHangHoa> LoHangHoa { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<PhanLoaiHoaDon> PhanLoaiHoaDon { get; set; }
        public virtual DbSet<QuyetDinhThau> QuyetDinhThau { get; set; }
        public virtual DbSet<QuyetDinhThauChiTiet> QuyetDinhThauChiTiet { get; set; }
        public virtual DbSet<THUOC_6061> THUOC_6061 { get; set; }
        public virtual DbSet<HoTriLieu> HoTriLieu { get; set; }
        public virtual DbSet<ThuocDuongDung> ThuocDuongDung { get; set; }
        public virtual DbSet<VATTU_YTE_6061> VATTU_YTE_6061 { get; set; }
        public virtual DbSet<DinhGiaHangHoa> DinhGiaHangHoa { get; set; }
        public virtual DbSet<v_ChiTietDonViHangHoa> v_ChiTietDonViHangHoa { get; set; }
    }
}
