//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiGiaHangHoa
    {
        public System.Guid ID { get; set; }
        public string Ten { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsGiaNhap { get; set; }
        public string MaDoiTuongThanhToan { get; set; }
    }
}
