//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucHuongBHYT
    {
        public int AutoID { get; set; }
        public string MaThe { get; set; }
        public string KiTuThu3 { get; set; }
        public Nullable<bool> PhanLoai { get; set; }
        public Nullable<double> MucHuongBH { get; set; }
        public Nullable<double> CPVC { get; set; }
        public Nullable<double> TT { get; set; }
        public Nullable<bool> HoatDong { get; set; }
    }
}
