//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuocGia
    {
        public int MA_QGIA { get; set; }
        public string ten_qg { get; set; }
        public string ten_vt { get; set; }
    }
}
