//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU_YTE_6061
    {
        public string MA_VAT_TU { get; set; }
        public string TEN_VAT_TU { get; set; }
        public string MA_NHOM_VTU { get; set; }
        public string DVT { get; set; }
    }
}
