//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.KhoChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DonViInfo
    {
        public System.Guid ID { get; set; }
        public System.Guid ThuocID { get; set; }
        public System.Guid DonViID { get; set; }
        public string Ten { get; set; }
        public decimal TiLeChuyenDoi { get; set; }
        public string MoTa { get; set; }
        public byte PhuongThucChuyenDoi { get; set; }
    }
}
