//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BVEntities : DbContext
    {
        public BVEntities()
            : base("name=BVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenDoiDonViThuoc> ChuyenDoiDonViThuoc { get; set; }
        public virtual DbSet<DonViThuoc> DonViThuoc { get; set; }
        public virtual DbSet<GiaThuoc> GiaThuoc { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<HoTriLieu> HoTriLieu { get; set; }
        public virtual DbSet<ThuocDuongDung> ThuocDuongDung { get; set; }
        public virtual DbSet<QuyetDinhThau> QuyetDinhThau { get; set; }
        public virtual DbSet<QuyetDinhThauChiTiet> QuyetDinhThauChiTiet { get; set; }
        public virtual DbSet<THUOC_6061> THUOC_6061 { get; set; }
        public virtual DbSet<Thuoc_VatTuYte> Thuoc_VatTuYte { get; set; }
        public virtual DbSet<VATTU_YTE_6061> VATTU_YTE_6061 { get; set; }
        public virtual DbSet<v_DonViInfo> v_DonViInfo { get; set; }
    }
}
