//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaThuoc
    {
        public System.Guid ID { get; set; }
        public System.Guid ThuocID { get; set; }
        public System.Guid DonViID { get; set; }
        public decimal GiaDichVu { get; set; }
        public Nullable<decimal> GiaBaoHiem { get; set; }
        public Nullable<decimal> GiaChinhSach { get; set; }
    }
}
