//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC_6061
    {
        public int THUOC_ID { get; set; }
        public string SO_DANG_KY { get; set; }
        public string TEN_THUOC { get; set; }
        public string MA_HOAT_CHAT { get; set; }
        public string HOAT_CHAT { get; set; }
        public string MA_DUONG_DUNG { get; set; }
        public string HAM_LUONG { get; set; }
        public string DONG_GOI { get; set; }
        public Nullable<int> LOAI_THUOC { get; set; }
        public Nullable<int> MA_NHOM_THUOC { get; set; }
        public string NGUY_CO_THUOC { get; set; }
    }
}
