//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel.Kho
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieu
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PhieuID { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.Guid> MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public string SoLo { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public string SoQuyeDinh { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<System.Guid> MaDonVi { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ChietKhau { get; set; }
        public Nullable<short> LoaiChietKhau { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    }
}
