//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongKhamBenh
    {
        public System.Guid ID { get; set; }
        public string MADV { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> ThuPhi { get; set; }
        public Nullable<double> GiaBHTN { get; set; }
        public Nullable<double> BHYT { get; set; }
        public string PhanLoaiNhomBHYT { get; set; }
        public Nullable<bool> HieuLuc { get; set; }
        public string MaBYT { get; set; }
        public string TenBYT { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<System.DateTime> NgayHetHieuLuc { get; set; }
    }
}
