//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanToc
    {
        public int DAN_TOC_Id { get; set; }
        public string TEN_DAN_TOC { get; set; }
        public string TEN_KHAC { get; set; }
    }
}
