//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDanh
    {
        public int ID_DiaDanh { get; set; }
        public string MaDiaDanh { get; set; }
        public string MaTinh { get; set; }
        public string TenTinh { get; set; }
        public string MaHuyen { get; set; }
        public string TenHuyen { get; set; }
        public string MaXa { get; set; }
        public string TenXa { get; set; }
        public string TenDayDu { get; set; }
        public string TenNganGon { get; set; }
    }
}
