//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu_
    {
        public int id { get; set; }
        public string MaTG { get; set; }
        public string MADV { get; set; }
        public string MaKhoa { get; set; }
        public string Nhom { get; set; }
        public string KhuVuc { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> ThuPhi { get; set; }
        public Nullable<double> GiaBHTN { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> Mien { get; set; }
        public Nullable<double> Khac { get; set; }
        public Nullable<double> TreEmDuoi6Tuoi { get; set; }
        public string PhanLoaiNhomBHYT { get; set; }
        public Nullable<bool> hienthi { get; set; }
        public Nullable<double> vip { get; set; }
        public Nullable<bool> VuotTuyen { get; set; }
        public string ThuTu { get; set; }
        public string notes { get; set; }
        public string TuTruc { get; set; }
        public string stt { get; set; }
        public string MaBYT { get; set; }
        public string MaKhoa_BYT { get; set; }
        public string MaDungChung { get; set; }
        public string TenBYT { get; set; }
        public Nullable<System.DateTime> ngayhieuluc { get; set; }
        public Nullable<System.DateTime> ngayhethieuluc { get; set; }
    }
}
