//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViHangHoa
    {
        public System.Guid ID { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> InActive { get; set; }
    }
}
