//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.PhieuDeNghiChiTiet = new HashSet<PhieuDeNghiChiTiet>();
            this.PhieuNhapChiTiet = new HashSet<PhieuNhapChiTiet>();
            this.PhieuXuatChiTiet = new HashSet<PhieuXuatChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string TenKhac { get; set; }
        public string HoatChat { get; set; }
        public string DuongDung { get; set; }
        public string HamLuong { get; set; }
        public string DongGoi { get; set; }
        public Nullable<int> LoaiThuoc { get; set; }
        public string NguyCoThuoc { get; set; }
        public string HoTriLieu { get; set; }
        public Nullable<System.Guid> DonViID { get; set; }
        public Nullable<int> OldID { get; set; }
        public Nullable<int> MaBHThamChieu { get; set; }
        public string PhanLoaiDuocID { get; set; }
        public Nullable<int> MaNhomBaoHiem { get; set; }
        public Nullable<bool> ThanhToanBaoHiem { get; set; }
        public string TyLeThanhToanBaoHiem { get; set; }
    
        public virtual DonViHangHoa DonViHangHoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDeNghiChiTiet> PhieuDeNghiChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapChiTiet> PhieuNhapChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatChiTiet> PhieuXuatChiTiet { get; set; }
    }
}
