//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_BHYT
    {
        public System.Guid ID { get; set; }
        public System.Guid HSCN_ID { get; set; }
        public string MA_THE { get; set; }
        public Nullable<System.DateTime> GT_THE_TU { get; set; }
        public Nullable<System.DateTime> GT_THE_DEN { get; set; }
        public bool InActive { get; set; }
        public string MA_DKBD { get; set; }
        public string DIACHI_DKBD { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
    }
}
