//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_DoiTuong
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> HSCaNhanID { get; set; }
        public Nullable<System.Guid> HSTiepNhanID { get; set; }
        public Nullable<System.Guid> HSDieuTriID { get; set; }
        public Nullable<System.Guid> DoiTuongID { get; set; }
        public string MaTheBHYT { get; set; }
        public string CoQuan { get; set; }
        public string CapBac { get; set; }
        public string ChucVu { get; set; }
        public string ThongTinKhac { get; set; }
    }
}
