//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public System.Guid ID { get; set; }
        public string MaKho { get; set; }
        public string TenKho { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public Nullable<int> LoaiKhoId { get; set; }
    
        public virtual KhoaPhong KhoaPhong { get; set; }
        public virtual LoaiKho LoaiKho { get; set; }
    }
}
