//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kho()
        {
            this.PhieuDeNghi = new HashSet<PhieuDeNghi>();
            this.PhieuDeNghi1 = new HashSet<PhieuDeNghi>();
            this.PhieuNhapKho = new HashSet<PhieuNhapKho>();
            this.PhieuTraThuoc = new HashSet<PhieuTraThuoc>();
            this.PhieuXuatKho = new HashSet<PhieuXuatKho>();
            this.PhieuXuatKho1 = new HashSet<PhieuXuatKho>();
            this.XuatTra = new HashSet<XuatTra>();
        }
    
        public System.Guid ID { get; set; }
        public string MaKho { get; set; }
        public string TenKho { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public Nullable<int> LoaiKhoId { get; set; }
    
        public virtual KhoaPhong KhoaPhong { get; set; }
        public virtual LoaiKho LoaiKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDeNghi> PhieuDeNghi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDeNghi> PhieuDeNghi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapKho> PhieuNhapKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuTraThuoc> PhieuTraThuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatKho> PhieuXuatKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatKho> PhieuXuatKho1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatTra> XuatTra { get; set; }
    }
}
