//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public int NguonNhapID { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string TinhThanh { get; set; }
        public string QuocGia { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string GhiChu { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
    }
}
