//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomDichVuBHYT
    {
        public int STT_NH { get; set; }
        public string TEN_NH { get; set; }
        public string TEN_RG { get; set; }
        public string CONGDUNG { get; set; }
        public string LOAI { get; set; }
        public Nullable<int> MaBYT { get; set; }
    }
}
