//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTraThuocChiTiet
    {
        public System.Guid ID { get; set; }
        public System.Guid PhieuTraThuocId { get; set; }
        public Nullable<System.Guid> PhieuXuatId { get; set; }
        public string MaPhieuXuat { get; set; }
        public System.Guid HangHoaID { get; set; }
        public double SoLuongTra { get; set; }
        public Nullable<double> DonGia { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuTraThuoc PhieuTraThuoc { get; set; }
        public virtual PhieuXuatKho PhieuXuatKho { get; set; }
    }
}
