//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhapKho()
        {
            this.PhieuNhapChiTiet = new HashSet<PhieuNhapChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string Ma { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public int MaNhaCungCap { get; set; }
        public string NhaCungCap { get; set; }
        public string NguoiCungCap { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> MaPhanLoaiHoaDon { get; set; }
        public string TenPhanLoaiHoaDon { get; set; }
        public Nullable<System.Guid> PhieuDeNghiId { get; set; }
        public Nullable<System.Guid> KhoId { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual PhanLoaiHoaDon PhanLoaiHoaDon { get; set; }
        public virtual PhieuDeNghi PhieuDeNghi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapChiTiet> PhieuNhapChiTiet { get; set; }
    }
}
