//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinBenhVien
    {
        public decimal ID { get; set; }
        public string MABV { get; set; }
        public string CQChuQuan { get; set; }
        public string TenBV { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string FAX { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string GhiChu { get; set; }
        public string TenKhoDuoc { get; set; }
        public string DCNhaThuoc { get; set; }
        public string MaDKBD { get; set; }
    }
}
