//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc_VatTuYteTonKho
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ThuocVtytID { get; set; }
        public string SoQuyetDinh { get; set; }
        public string PhanLoaiDuocID { get; set; }
        public string MaHoatChat { get; set; }
        public Nullable<decimal> SoLuongTon { get; set; }
        public Nullable<decimal> SoLuongDaNhap { get; set; }
        public string SoLuongDaXuat { get; set; }
        public string SoLo { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
    }
}
