//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BV.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XuatTra()
        {
            this.XuatTraChiTiet = new HashSet<XuatTraChiTiet>();
        }
    
        public System.Guid ID { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.Guid> NguoiLap { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.Guid> KhoId { get; set; }
        public string LyDo { get; set; }
        public System.Guid PhieuTraThuocID { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual PhieuTraThuoc PhieuTraThuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatTraChiTiet> XuatTraChiTiet { get; set; }
    }
}
